### ISSUE TITLE
Cursor position after completion.

### ISSUE THREAD

**Issue by aca** [aca/emmet-ls#1]
Can be supported with the help of vim-vsnip.

**Comment by kabouzeid** [comment]
is fixed, should be closed

**Comment by pedro757** [comment]
When I write something like `table>tr*3` I get this

```html
<table>
  <tr> ${1} </tr>
  <tr> ${2} </tr>
  <tr> ${3} </tr>
</table>
```
Those `${1}` `${2}` `${3}` should be jumpable.

I'm using [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) and [luasnip](https://github.com/L3MON4D3/LuaSnip)

**Comment by pedro757** [comment]
@aca What do you think of this?

https://github.com/hrsh7th/nvim-cmp/issues/97#issuecomment-907731238
