### ISSUE TITLE
Support for jsx

### ISSUE THREAD

**Issue by DONofDESTROY** [aca/emmet-ls#10]
thx for the lsp, works great.
Is there any support for jsx or future plans.
here is my config for reference

``` lua
local capabilities = vim.lsp.protocol.make_client_capabilities()

capabilities.textDocument.completion.completionItem.snippetSupport = true

require "lspconfig/configs".emmet_ls = {
  default_config = {
    cmd = {"emmet-ls", "--stdio"},
    filetypes = {"html", "css", "javascript", "javascriptreact", "javascript.jsx"},
    root_dir = require "lspconfig".util.root_pattern(".git", vim.fn.getcwd())
  }
}

require "lspconfig".emmet_ls.setup {
  on_attach = require "nvim-lsp".common_on_attach
}

```

**Comment by prncss-xyz** [comment]
and tsx :-)

**Comment by kozer** [comment]
I have created a new package based on this repo named `emmet-language-server`. It also includes the changes of the pr that is opened in the  current repo (fix snippet expanding).
Till this repo gets life again you can install it with `npm i -g emmet-language-server`

**Comment by ShiChenCong** [comment]
https://github.com/pedro757/emmet found the repo,base on lsp,support jsx

**Comment by Ali-Aref** [comment]
Will you support `jsx`/`tsx` or not? kindly give us a feedback as **martinsione** mentioned this is the default `nvim-lsp-install` and we would prefer this if it supports else just let as know. 🙂

**Comment by aca** [comment]
Sorry for late response. Updated.

**Comment by aca** [comment]
lspconfig should also be updated. Will check it later. 
You have to customize lspconfig for now.
```
local lspconfig = require("lspconfig")
lspconfig.emmet_ls.setup({
    -- capabilities = capabilities,
    -- on_attach = on_attach,
    filetypes = { "html", "css", "typescriptreact", "javascriptreact" },
})
```

**Comment by santigo-zero** [comment]
Do we have to configure anything else for jsx and tsx files to use className instead of class?
