### ISSUE TITLE
Support for template engines (blade, vue, heex, etc)

### ISSUE THREAD

**Issue by pbogut** [aca/emmet-ls#17]
Hey, this is great, I like it very much.

Have issue though, here's the thing: You can add `filetype` in your lsp configuration and that will work, but then this LS defaults to `css` snippets.
So if I add `blade` or `php` to nvim lsp file types language server is running but it gives snippets for `css`.

Maybe it would be better to add configuration option for lsp and allow to add file types separately for `css` and `html` snippet functionality.

Many languages use different templates for `html` so maybe it would be better to default on html rather than css.
I didn't dig too much into the code, but would it be possible to get both work on same file as 2 separate completion items?
Html / Vue can mix html and css in one file, so that would be nice to have as well, maybe as an option.

There is somehow related PR #16 that is adding blade support, but there are many more different template engines that I would like to have support for.

I can do PR myself if you are accepting the concept of additional configuration, or enabling both html / css in one file?

**Comment by butschi** [comment]
I totally agree. There is now another PR #24 with the same goal, but like @pbogut said there are many templating languages.

Emmets power lies in the `html` generation, imho. It should be the default until a specialised version for multi-language files like `.vue` gets implemented.

**Comment by pbogut** [comment]
I've implemented it for myself in my fork, but it changes a lot of code so I hasitate to create PR.


* Sent from a mobile device. Please excuse brevity and typos.

**Comment by pbogut** [comment]
If anyone wants to try it here it is:
[fork](https://github.com/pbogut/emmet-ls/commits/master) and [config](https://github.com/pbogut/dotfiles/blob/master/config/nvim/lua/plugins/lsp/emmet_ls.lua).
I'm happy to split it in bunch of smaller commits if @aca is willing to accept PR with that config change.

**Comment by niklasmohrin** [comment]
Is there any chance the changes from @pbogut could be merged @aca? Your LS integrates very well into my workflow (thanks a lot for your work!), but unfortunately only CSS snippets are suggested in my django template files. In contrast, the config that @pbogut linked to is the one that I, as a user, would really like to have - it also eliminates all future issues and debate in this matter. For what it is worth, I am running the linked fork and it works without any issues so far

**Comment by LKummer** [comment]
In #39 HTML syntax was made the default for unknown filetypes.
