### ISSUE TITLE
snippet text still alive after hit enter

### ISSUE THREAD

**Issue by tin-pham** [aca/emmet-ls#21]
![image](https://user-images.githubusercontent.com/20679090/143666730-0cba07d7-241a-491e-8233-1e5d18520b9e.png)

![image](https://user-images.githubusercontent.com/20679090/143666750-eb0304e7-ea87-4b19-ba8c-56fc46b54360.png)

**Comment by anoopd** [comment]
Me too having the same problem :(
![Untitled](https://user-images.githubusercontent.com/925418/143680284-dfbad8f6-e24d-4dc0-8c71-8943a92e9a58.png)

**Comment by dasraab** [comment]
same problem here :(

**Comment by P1P0S** [comment]
same
![image](https://user-images.githubusercontent.com/62353660/143780261-f1ea1657-4ec6-45d8-b7d5-b5ca1a826b54.png)

**Comment by tin-pham** [comment]
> same problem here :(



> Me too having the same problem :( ![Untitled](https://user-images.githubusercontent.com/925418/143680284-dfbad8f6-e24d-4dc0-8c71-8943a92e9a58.png)

I think we need to move on to the ls_emmet instead https://github.com/pedro757/emmet, it worked for me

**Comment by gegoune** [comment]
There was an update very recently. Update your version. This issue can be closed.

**Comment by anoopd** [comment]
ok
