### ISSUE TITLE
lspconfig: Autostart for emmet_ls failed: matching root directory not detected 

### ISSUE THREAD

**Issue by mondenoir** [aca/emmet-ls#22]
After a recent update, “emmet_ls” just stopped working completely and prompted the following error message whenever an html or css file is opened:

<img width="640" alt="Screen Shot 2021-12-01 at 1 13 43 AM" src="https://user-images.githubusercontent.com/35069772/144099906-6fb7d0e1-1754-4c7f-9f54-d89671c78d60.png">

The following is my config file:

```
-- Setup lspconfig.
  local capabilities = vim.lsp.protocol.make_client_capabilities()
  capabilities.textDocument.completion.completionItem.snippetSupport = true  
  
-- Emmet 
  require'lspconfig/configs'.emmet_ls = {
    default_config = {
      cmd = { 'emmet-ls', '--stdio' };
      filetypes = { 'html', 'css', 'scss', 'xml', 'pug', 'sass'};
      root_dir = function(fname)
        return vim.loop.cwd()
      end;
      settings = {};
    };
  }

-- Language Servers:
  local langservers = {
    'cssls',
    'html',
    'emmet_ls',
    'pylsp',
    'tsserver',
  } 

  for _, server in ipairs(langservers) do
    require'lspconfig'[server].setup {
      capabilities = capabilities
    }
  end
```

To troubleshoot this, I did clear out my config file and pasted in only the suggested configuration code below from GitHub but the same error message still pop-up indicating “root directory not detected”

```
local lspconfig = require'lspconfig'
local configs = require'lspconfig/configs'    

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

if not lspconfig.emmet_ls then    
  configs.emmet_ls = {    
    default_config = {    
      cmd = {'emmet-ls', '--stdio'};
      filetypes = {'html', 'css', 'blade'};
      root_dir = function(fname)    
        return vim.loop.cwd()
      end;    
      settings = {};    
    };    
  }    
end    
lspconfig.emmet_ls.setup{ capabilities = capabilities; }
```

All the other language servers are working properly except “emmet_ls.” Any reply would be great appreciated, million thanks in advance.

**Comment by carlitux** [comment]
@mondenoir it is not related with emmet-ls it is a message from neovim LSP that the LSP server was not started because your root directory was not detected.

lspconfig the default root_dir is a git repository make sure it exists of modify your config

default emmet config https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#emmet_ls

**Comment by carlitux** [comment]
@mondenoir the basic ussage must be

`lua
local lspconfig = require'lspconfig'

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
lspconfig.emmet_ls.setup{ capabilities = capabilities; }
`

**Comment by mondenoir** [comment]
@carlitux Thanks to your prompt and elaborate reply, "emmet-ls" work perfectly after initiating a git repo in the project's directory. This process wasn't required before updating my plugins, is there a way to configure the "root_dir" without having to initiate git for "emmet-ls" to work?  Once again, thank you "carlitux" you truly are a lifesaver :)

**Comment by carlitux** [comment]
@mondenoir not sure if will work but you can try, next will use your current working directory as your root_dir.

```lua
local lspconfig = require'lspconfig'

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
lspconfig.emmet_ls.setup{ 
    capabilities = capabilities,
    root_dir = function(fname)    
        return vim.loop.cwd()
    end,
}
```

**Comment by mondenoir** [comment]
@carlitux You did it again my friend :) 

Due to your reply, I was able to tweaked my config file and now everything works just like before the update 👍👍👍 As a newcomer to the Vim community, you have no clue how much these replies means to me. Thanks a million carlitux 🙏🙏🙏

PS: I will leave a copy of the configuration below to illustrate what I did wrong and what carlitux did to help me correct the mistakes:

```
-- Defining lspconfig + capabilities 
  local lspconfig = require'lspconfig'
  local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
  capabilities.textDocument.completion.completionItem.snippetSupport = true

-- Emmet 
  lspconfig.emmet_ls.setup{ 
      capabilities = capabilities,
      filetypes = { 'html', 'css', 'scss', 'xml', 'pug', 'sass'};
      root_dir = function(fname)    
          return vim.loop.cwd()
      end,
  }

-- Language Servers:
  local langservers = {
    'cssls',
    'html',
    'pylsp',
    'tsserver',
  } 

-- Setting up lspconfig
  for _, server in ipairs(langservers) do
    lspconfig[server].setup {
      capabilities = capabilities
    }
  end
```
