### ISSUE TITLE
Adding scss

### ISSUE THREAD

**Issue by bryant-the-coder** [aca/emmet-ls#25]
Is it possible for emmet-ls to work in scss? As for now it only works on css and html (for me)

**Comment by olrtg** [comment]
You can refer to https://github.com/aca/emmet-ls/issues/26#issuecomment-1017131472 to see how you can add more filetypes to enable emmet-ls.

**Comment by olrtg** [comment]
@aca I think we can close this since `emmet-ls` does support `scss` for some time now 🤔
