### ISSUE TITLE
cant use emmet

### ISSUE THREAD

**Issue by bryant-the-coder** [aca/emmet-ls#26]
```
[lspconfig] Autostart for emmet_ls failed: matching root directory not detected.
[lspconfig] Autostart for emmet_ls failed: matching root directory not detected.
```

da error is this. i cant even understand what the heck it is saying

**Comment by bryant-the-coder** [comment]
am on windows 10

**Comment by Ali-Aref** [comment]
Same here on Linux Manjaro, Any solutions?

**Comment by bryant-the-coder** [comment]
breh idk... the owner have been offline for weeks months

**Comment by Ali-Aref** [comment]
here is my current solution (setting the root dir) as `root_dir` 

`
root_dir = function(fname)    
    return vim.loop.cwd()
end,
`
so my settings would look like
`
lspconfig.emmet_ls.setup{ 
    capabilities = capabilities,
    filetypes = { 'html', 'css', 'scss', 'xml', 'pug', 'sass', 'jsx', 'tsx'};
    root_dir = function(fname)    
        return vim.loop.cwd()
    end,
}
`
