### ISSUE TITLE
Support for htmldjango files

### ISSUE THREAD

**Issue by milkias17** [aca/emmet-ls#29]
The language server gets confused in htmldjango files and expands snippets as if they are css files. Would be great to use emmet-ls in htmldjango files as well.

**Comment by JanValiska** [comment]
Same for PHP Nette Framework and it's template engine called Latte. It's basically HTML with embeeded template syntax.
I looked at emmet-ls source code, but I cannot find a way to tell that also files with .latte extension should be treated as html.

It's same issue as @milkias17 reported.

**Comment by milkias17** [comment]
@JanValiska  I got it working so what you need to do is in the emmet-ls/out/server.js there is a line that says: `if languageID === "html"` so just add to that conditional the filetype like `if languageID === "html" || languageID === "htmldjango"` I would do a pull request but couldn't get the master branch working.
