### ISSUE TITLE
Weird behaviour with neovim builtin lsp and completion-nvim

### ISSUE THREAD

**Issue by blackCauldron7** [aca/emmet-ls#3]
When expanding the emmet abbreviation is not replaced and newlines and indentation doesnt work.
Example
`div>h.`
Converts to
`div>h.<div> 	<h class=""></h> </div>`

**Comment by aca** [comment]
hmm. Do you have https://github.com/hrsh7th/vim-vsnip installed? and set snippet support to yes?
```
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
```

**Comment by blackCauldron7** [comment]
> hmm. Do you have https://github.com/hrsh7th/vim-vsnip installed? and set snippet support to yes?
> 
> ```
> local capabilities = vim.lsp.protocol.make_client_capabilities()
> capabilities.textDocument.completion.completionItem.snippetSupport = true
> ```

yes i have those. i copied them from the readme.

**Comment by blackCauldron7** [comment]
The issue was fixed by reinstalling vsnip.
