### ISSUE TITLE
class not expanding to className .js files

### ISSUE THREAD

**Issue by Ddystopia** [aca/emmet-ls#34]
![Screenshot](https://i.imgur.com/Jdiq9nm.png)

emmetio/emmet has config option for this purpose

![Emmet option](https://i.imgur.com/etzRwQx.png)

**Comment by Hyoihz** [comment]
Have you find any solution to this?

**Comment by Hyoihz** [comment]
Have you found any solution to this?

**Comment by ArifulProtik** [comment]
Any solution yet?

**Comment by filipekiss** [comment]
I have forked and made the fix, you can find instructions on how to use my fork in the [pull-request](https://github.com/aca/emmet-ls/pull/40). You can use that until it's merged upstream. :)

**Comment by LKummer** [comment]
It is now fixed [as of the 0.3.0 release](https://github.com/aca/emmet-ls/releases/tag/0.3.0).
Please comment or open a new issue if anything does not work as expected.
