### ISSUE TITLE
Support `html` tagged-template-literals

### ISSUE THREAD

**Issue by bennypowers** [aca/emmet-ls#35]
Please consider adding support for `html`-tagged template literals, such as you'd find with [lit](https://lit.dev), [FAST](https://fast.design), [htm](https://github.com/developit/htm), and others.

**Current Behaviour**

```js
// example.js
html`
  div>button{hi}+input[pattern="[0-9]{3}"]
`
//                                       ^ cursor on ] here
```

No snippet suggested

**Requested Behaviour**

Snippet suggested:

<img width="671" alt="Screen Shot 2022-03-10 at 8 17 41" src="https://user-images.githubusercontent.com/1466420/157669644-640e3a09-9035-4f93-bc74-288774222c82.png">

**Comment by olrtg** [comment]
Hey @bennypowers this is working for me! So I'm going to close this for the mean time. Let me know if I can help you in any way.
