### ISSUE TITLE
django template support

### ISSUE THREAD

**Issue by gmr458** [aca/emmet-ls#38]
The index.html file is a django template and that's why emmet doesn't work as expected, the abc.html file is normal html and if it works, it would be great to have emmet work in django templates as well.
<video src="https://user-images.githubusercontent.com/53343401/163697643-f43ec673-dad1-4839-a2c7-e6e1b34bed28.mp4" width="100%"></video>

**Comment by kofm** [comment]
It seems that the file is recognised as CSS, maybe because of the curly braces?

**Comment by LKummer** [comment]
[Since the 0.3.0 release](https://github.com/aca/emmet-ls/releases/tag/0.3.0) Django templates are identified correctly as HTML.
I am closing this. Please comment or open a new issue if something does not work as expected.
