### ISSUE TITLE
Unable to get css snippets

### ISSUE THREAD

**Issue by gegoune** [aca/emmet-ls#4]
With nvim's builtin LSP server and completion.nvim, with configuration such as:

```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

local configs = require "lspconfig/configs"

configs.emmet_ls = {
  default_config = {
    cmd = {"emmet-ls", "--stdio"},
    filetypes = {"html", "css", "vue", "scss"},
    root_dir = function()
      return vim.loop.cwd()
    end,
    settings = {}
  }
}

lspconfig.emmet_ls.setup {
  on_attach = on_attach,
  capabilities = capabilities
}
```

I am not getting any snippet completions candidates for emmet in `css`, `vue` and `scss` files. Should it work at all or am I misconfiguring something?

Thanks.

**Comment by Vanderscycle** [comment]
Not being overly helpful, but emmet-ls works flawlessly in html files but its somewhat inconsistent when using vue. Like sometimes I get the completion sometimes it leaves it as is.
