### ISSUE TITLE
How to add `.gohtml` files to the list of available files

### ISSUE THREAD

**Issue by bab014** [aca/emmet-ls#45]
So I've been trying for hours to get this to work myself and here I am. 

I added this line to my config
```lua
filetypes = { 'gohtml', 'html', 'css' },
```
But that doesn't actually allow me to use emmet with `gohtml` filetypes. 

Emmet works with html and css.

What am I doing wrong?

**Comment by kuromika** [comment]
I have a similar problem, I'm trying to make it work on Pug files, I'm using lsp-zero and have this piece of code: 
```
lsp.configure('emmet-ls', {
    filetypes = { "html", "typescriptreact", "javascriptreact", "css",
    "sass", "scss", "less", "pug",  "eruby" }
})
```

but when I open a pug file emmet-ls isn't getting attached, and when I open a tsx file and run `:LspInfo`, emmet-ls doesn't show 'Pug' in its file types.

**Comment by olrtg** [comment]
I'm closing this for the mean time. The fixes that were proposed by @LKummer and @kuromika should work. @bab014 if you have any other problem related to this please lmk.
