### ISSUE TITLE
PHP treated as stylesheet

### ISSUE THREAD

**Issue by BitInByte** [aca/emmet-ls#49]
Hello guys. I'm currently facing an issue that I don't know if there is something that I'm missing to set up. Basically, every time that I try to use emmet, it will show me the snippets for stylesheets instead of showing snippets for html. For example, the ! sign on the php file results in !important instead of the html scaffold. I'm I missing some configuration?

Thanks in advance...

**Comment by LKummer** [comment]
You may be running an outdated version, please try running this command to get the latest release:

```
npm install --global emmet-ls@latest
```

**Comment by BitInByte** [comment]
It worked @LKummer thank you so muchhhhh
