### ISSUE TITLE
hrsh7th/nvim-compe support request.

### ISSUE THREAD

**Issue by singlexyz** [aca/emmet-ls#5]
hrsh7th/nvim-compe support request.

**Comment by cloggier** [comment]
@singlexyz for now you can use https://github.com/windwp/emmet-ls

**Comment by ofrades** [comment]
@cloggier how do you install the server from windwp fork?

**Comment by cloggier** [comment]
@ofrades https://github.com/hrsh7th/nvim-compe/issues/190#issuecomment-789282059

**Comment by singlexyz** [comment]
> https://github.com/windwp/emmet-ls

👍 Thanks a lot.

**Comment by aca** [comment]
It seems like @windwp resolved all the issues. Sorry for my late response, life is harsh, too busy for me right now.
@windwp If you are okay, could you send a PR? I can release it through npm.

**Comment by aca** [comment]
There's still an issue with expanding emmet like ```ul>li.item$*5```.
I'll create another issue for it.

**Comment by kabouzeid** [comment]
@aca could you update the npm release with the fixes from windwp? :)
