### ISSUE TITLE
'class' being suggested instead of 'className' in a .js file

### ISSUE THREAD

**Issue by beetol** [aca/emmet-ls#58]
I'm having an issue where using `div.rhs_cls` keeps suggesting `<div class="rhs_cls"></div>` instead of `<div className="rhs_cls"></div>`

It works perfectly on jsx files, but not js files

Am I missing something or are js files not supported ?

I have the following lsp config:

```
lspconfig.emmet_ls.setup({
  on_attach = on_attach,
  capabilities = vim.lsp.protocol.make_client_capabilities(),
  ['capabilities.textDocument.completion.completionItem.snippetSupport'] = true,
  filetypes = { 'css', 'sass', 'scss', 'less', 'javascript' },

  init_options = {
    javascript = {
      options = {
        ["markup.attributes"] = { class = "className" },
      }
    },
    jsx = {
      options = {
        ["markup.attributes"] = { class = "className" },
      }
    },
    javascriptreact = {
      options = {
        ["markup.attributes"] = { class = "className" },
      }
    }
  }
})
```

**Comment by olrtg** [comment]
Hi @beetol! looking at the source code my guess is that javascript is getting treated as html ([see this part](https://github.com/aca/emmet-ls/blob/master/src/server.ts#L171)).. but I don't know why your config is not working.. did you test if your `markup.attributes` config is working by doing the opposite? something like this:

```lua
javascriptreact = {
    options = {
        ["markup.attributes"] = { class = "class" },
    }
}
```

**Comment by olrtg** [comment]
Hey @beetol now that #60 is merged you can do this:

```lua
  init_options = {
    js = {
      options = {
        ["markup.attributes"] = { class= "className" },
      },
    },
  },
```

Please let me know if that fixes your problem!

**Comment by beetol** [comment]
Thanks @olrtg! 

Just tried it but I seem to get the same issue. I'm using EcoVim so I may need to tweak some configurations to find the culprit. Will let you know once it does work. Thanks again!

**Comment by beetol** [comment]
Woohoo🥳 It works. Closing.

**Comment by beetol** [comment]
Woohoo🥳 It works. Closing.
