### ISSUE TITLE
emmet-ls ignoring options in tsx/jsx file

### ISSUE THREAD

**Issue by RannyArcher** [aca/emmet-ls#65]
**lua/custom/configs/lspconfig.lua:**
```lua
...
lspconfig.emmet_ls.setup {
  on_attach = on_attach,
  capabilities = capabilities,
  filetypes = {
    "css",
    "eruby",
    "html",
    "javascript",
    "javascriptreact",
    "less",
    "sass",
    "scss",
    "svelte",
    "pug",
    "typescriptreact",
    "vue",
  },
  init_options = {
    html = {
      options = {
        -- For possible options, see: https://github.com/emmetio/emmet/blob/master/src/config.ts#L79-L267
        ["output.selfClosingStyle"] = "xhtml",
      },
    },
  },
}
```

**index.tsx**

```tsx
input /// clicking enter in completion list -----> <input type="text">
```

i was expecting to get `<input type="text" />` _notice the closing slash_, that didn't work i even tried to change html to typescriptreact. and nothing.

is that bug or am i stupid  guys : ).

**Comment by olrtg** [comment]
I think you should use `jsx` instead of `html` like this:

```lua
jsx = {
  options = {
    ...
  }
}
```
The filetype `javascriptreact` and `typescriptreact` maps to `jsx` for emmet. Take a look at the mapping here: https://github.com/aca/emmet-ls/blob/master/src/server.ts#L142-L152

Let me know if that helps!

**Comment by RannyArcher** [comment]
thanks bro i already discovered i'm misunderstanding the config file. and didnt close the issue yet ... thanks agaain
