### ISSUE TITLE
Original text remains when expanding `ul>li.item$*5.` with nvim-compe

### ISSUE THREAD

**Issue by aca** [aca/emmet-ls#7]
Probably issue with nvim-compe.

**Comment by siddhantk232** [comment]
Same problem in completion.vim also.

**Comment by n3wborn** [comment]
Impossible to use with nvim-compe too (same as coc-emmet though)

**Comment by nawfalmrouyan** [comment]
fixed in latest nvim-compe

**Comment by dasraab** [comment]
same problem here with nvim-cmp and vsnips

**Comment by MonstrousOgre** [comment]
I'm also facing this problem with nvim-cmp and luasnip

**Comment by imSafdarAwan** [comment]
> I'm also facing this problem with nvim-cmp and luasnip

same issue

**Comment by RaafatTurki** [comment]
Any clue so far?, I'd like to take a crack at this any leads would be helpful.
